// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: styles.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum AppearanceMetadata: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case dark // = 0
  case light // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .dark
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .dark
    case 1: self = .light
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .dark: return 0
    case .light: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension AppearanceMetadata: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [AppearanceMetadata] = [
    .dark,
    .light,
  ]
}

#endif  // swift(>=4.2)

public struct StyleSetMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var styles: [StyleMetadata] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct StyleMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// unique id of the style which correspond to the directory name
  public var id: String = String()

  public var title: String = String()

  public var stylesheets: [StylesheetMetadata] = []

  public var stylePreviews: Dictionary<String,TextStylePreviewMetadata> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct StylesheetMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var name: String = String()

  public var appearances: [AppearanceMetadata] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct TextStylePreviewMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var body: Color {
    get {return _storage._body ?? Color()}
    set {_uniqueStorage()._body = newValue}
  }
  /// Returns true if `body` has been explicitly set.
  public var hasBody: Bool {return _storage._body != nil}
  /// Clears the value of `body`. Subsequent reads from it will return its default value.
  public mutating func clearBody() {_uniqueStorage()._body = nil}

  public var h1: Color {
    get {return _storage._h1 ?? Color()}
    set {_uniqueStorage()._h1 = newValue}
  }
  /// Returns true if `h1` has been explicitly set.
  public var hasH1: Bool {return _storage._h1 != nil}
  /// Clears the value of `h1`. Subsequent reads from it will return its default value.
  public mutating func clearH1() {_uniqueStorage()._h1 = nil}

  public var h2: Color {
    get {return _storage._h2 ?? Color()}
    set {_uniqueStorage()._h2 = newValue}
  }
  /// Returns true if `h2` has been explicitly set.
  public var hasH2: Bool {return _storage._h2 != nil}
  /// Clears the value of `h2`. Subsequent reads from it will return its default value.
  public mutating func clearH2() {_uniqueStorage()._h2 = nil}

  public var h3: Color {
    get {return _storage._h3 ?? Color()}
    set {_uniqueStorage()._h3 = newValue}
  }
  /// Returns true if `h3` has been explicitly set.
  public var hasH3: Bool {return _storage._h3 != nil}
  /// Clears the value of `h3`. Subsequent reads from it will return its default value.
  public mutating func clearH3() {_uniqueStorage()._h3 = nil}

  public var h4: Color {
    get {return _storage._h4 ?? Color()}
    set {_uniqueStorage()._h4 = newValue}
  }
  /// Returns true if `h4` has been explicitly set.
  public var hasH4: Bool {return _storage._h4 != nil}
  /// Clears the value of `h4`. Subsequent reads from it will return its default value.
  public mutating func clearH4() {_uniqueStorage()._h4 = nil}

  public var h5: Color {
    get {return _storage._h5 ?? Color()}
    set {_uniqueStorage()._h5 = newValue}
  }
  /// Returns true if `h5` has been explicitly set.
  public var hasH5: Bool {return _storage._h5 != nil}
  /// Clears the value of `h5`. Subsequent reads from it will return its default value.
  public mutating func clearH5() {_uniqueStorage()._h5 = nil}

  public var h6: Color {
    get {return _storage._h6 ?? Color()}
    set {_uniqueStorage()._h6 = newValue}
  }
  /// Returns true if `h6` has been explicitly set.
  public var hasH6: Bool {return _storage._h6 != nil}
  /// Clears the value of `h6`. Subsequent reads from it will return its default value.
  public mutating func clearH6() {_uniqueStorage()._h6 = nil}

  public var code: Color {
    get {return _storage._code ?? Color()}
    set {_uniqueStorage()._code = newValue}
  }
  /// Returns true if `code` has been explicitly set.
  public var hasCode: Bool {return _storage._code != nil}
  /// Clears the value of `code`. Subsequent reads from it will return its default value.
  public mutating func clearCode() {_uniqueStorage()._code = nil}

  public var hr: Color {
    get {return _storage._hr ?? Color()}
    set {_uniqueStorage()._hr = newValue}
  }
  /// Returns true if `hr` has been explicitly set.
  public var hasHr: Bool {return _storage._hr != nil}
  /// Clears the value of `hr`. Subsequent reads from it will return its default value.
  public mutating func clearHr() {_uniqueStorage()._hr = nil}

  public var blockquote: Color {
    get {return _storage._blockquote ?? Color()}
    set {_uniqueStorage()._blockquote = newValue}
  }
  /// Returns true if `blockquote` has been explicitly set.
  public var hasBlockquote: Bool {return _storage._blockquote != nil}
  /// Clears the value of `blockquote`. Subsequent reads from it will return its default value.
  public mutating func clearBlockquote() {_uniqueStorage()._blockquote = nil}

  public var p: Color {
    get {return _storage._p ?? Color()}
    set {_uniqueStorage()._p = newValue}
  }
  /// Returns true if `p` has been explicitly set.
  public var hasP: Bool {return _storage._p != nil}
  /// Clears the value of `p`. Subsequent reads from it will return its default value.
  public mutating func clearP() {_uniqueStorage()._p = nil}

  public var h1Tag: Color {
    get {return _storage._h1Tag ?? Color()}
    set {_uniqueStorage()._h1Tag = newValue}
  }
  /// Returns true if `h1Tag` has been explicitly set.
  public var hasH1Tag: Bool {return _storage._h1Tag != nil}
  /// Clears the value of `h1Tag`. Subsequent reads from it will return its default value.
  public mutating func clearH1Tag() {_uniqueStorage()._h1Tag = nil}

  public var h2Tag: Color {
    get {return _storage._h2Tag ?? Color()}
    set {_uniqueStorage()._h2Tag = newValue}
  }
  /// Returns true if `h2Tag` has been explicitly set.
  public var hasH2Tag: Bool {return _storage._h2Tag != nil}
  /// Clears the value of `h2Tag`. Subsequent reads from it will return its default value.
  public mutating func clearH2Tag() {_uniqueStorage()._h2Tag = nil}

  public var h3Tag: Color {
    get {return _storage._h3Tag ?? Color()}
    set {_uniqueStorage()._h3Tag = newValue}
  }
  /// Returns true if `h3Tag` has been explicitly set.
  public var hasH3Tag: Bool {return _storage._h3Tag != nil}
  /// Clears the value of `h3Tag`. Subsequent reads from it will return its default value.
  public mutating func clearH3Tag() {_uniqueStorage()._h3Tag = nil}

  public var h4Tag: Color {
    get {return _storage._h4Tag ?? Color()}
    set {_uniqueStorage()._h4Tag = newValue}
  }
  /// Returns true if `h4Tag` has been explicitly set.
  public var hasH4Tag: Bool {return _storage._h4Tag != nil}
  /// Clears the value of `h4Tag`. Subsequent reads from it will return its default value.
  public mutating func clearH4Tag() {_uniqueStorage()._h4Tag = nil}

  public var h5Tag: Color {
    get {return _storage._h5Tag ?? Color()}
    set {_uniqueStorage()._h5Tag = newValue}
  }
  /// Returns true if `h5Tag` has been explicitly set.
  public var hasH5Tag: Bool {return _storage._h5Tag != nil}
  /// Clears the value of `h5Tag`. Subsequent reads from it will return its default value.
  public mutating func clearH5Tag() {_uniqueStorage()._h5Tag = nil}

  public var h6Tag: Color {
    get {return _storage._h6Tag ?? Color()}
    set {_uniqueStorage()._h6Tag = newValue}
  }
  /// Returns true if `h6Tag` has been explicitly set.
  public var hasH6Tag: Bool {return _storage._h6Tag != nil}
  /// Clears the value of `h6Tag`. Subsequent reads from it will return its default value.
  public mutating func clearH6Tag() {_uniqueStorage()._h6Tag = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Color {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The amount of red in the color as a value in the interval [0, 1].
  public var red: Float {
    get {return _storage._red}
    set {_uniqueStorage()._red = newValue}
  }

  /// The amount of green in the color as a value in the interval [0, 1].
  public var green: Float {
    get {return _storage._green}
    set {_uniqueStorage()._green = newValue}
  }

  /// The amount of blue in the color as a value in the interval [0, 1].
  public var blue: Float {
    get {return _storage._blue}
    set {_uniqueStorage()._blue = newValue}
  }

  /// The fraction of this color that should be applied to the pixel. That is,
  /// the final pixel color is defined by the equation:
  ///
  ///   pixel color = alpha * (this color) + (1.0 - alpha) * (background color)
  ///
  /// This means that a value of 1.0 corresponds to a solid color, whereas
  /// a value of 0.0 corresponds to a completely transparent color. This
  /// uses a wrapper message rather than a simple float scalar so that it is
  /// possible to distinguish between a default value and the value being unset.
  /// If omitted, this color object is to be rendered as a solid color
  /// (as if the alpha value had been explicitly given with a value of 1.0).
  public var alpha: SwiftProtobuf.Google_Protobuf_FloatValue {
    get {return _storage._alpha ?? SwiftProtobuf.Google_Protobuf_FloatValue()}
    set {_uniqueStorage()._alpha = newValue}
  }
  /// Returns true if `alpha` has been explicitly set.
  public var hasAlpha: Bool {return _storage._alpha != nil}
  /// Clears the value of `alpha`. Subsequent reads from it will return its default value.
  public mutating func clearAlpha() {_uniqueStorage()._alpha = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension AppearanceMetadata: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "dark"),
    1: .same(proto: "light"),
  ]
}

extension StyleSetMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "StyleSetMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "styles"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.styles)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.styles.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.styles, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: StyleSetMetadata, rhs: StyleSetMetadata) -> Bool {
    if lhs.styles != rhs.styles {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension StyleMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "StyleMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "title"),
    3: .same(proto: "stylesheets"),
    4: .same(proto: "stylePreviews"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.id)
      case 2: try decoder.decodeSingularStringField(value: &self.title)
      case 3: try decoder.decodeRepeatedMessageField(value: &self.stylesheets)
      case 4: try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,TextStylePreviewMetadata>.self, value: &self.stylePreviews)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if !self.stylesheets.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.stylesheets, fieldNumber: 3)
    }
    if !self.stylePreviews.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,TextStylePreviewMetadata>.self, value: self.stylePreviews, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: StyleMetadata, rhs: StyleMetadata) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.title != rhs.title {return false}
    if lhs.stylesheets != rhs.stylesheets {return false}
    if lhs.stylePreviews != rhs.stylePreviews {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension StylesheetMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "StylesheetMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
    3: .same(proto: "appearances"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.id)
      case 2: try decoder.decodeSingularStringField(value: &self.name)
      case 3: try decoder.decodeRepeatedEnumField(value: &self.appearances)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.appearances.isEmpty {
      try visitor.visitPackedEnumField(value: self.appearances, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: StylesheetMetadata, rhs: StylesheetMetadata) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.appearances != rhs.appearances {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension TextStylePreviewMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "TextStylePreviewMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "body"),
    2: .same(proto: "h1"),
    3: .same(proto: "h2"),
    4: .same(proto: "h3"),
    5: .same(proto: "h4"),
    6: .same(proto: "h5"),
    7: .same(proto: "h6"),
    8: .same(proto: "code"),
    9: .same(proto: "hr"),
    10: .same(proto: "blockquote"),
    11: .same(proto: "p"),
    12: .same(proto: "h1Tag"),
    13: .same(proto: "h2Tag"),
    14: .same(proto: "h3Tag"),
    15: .same(proto: "h4Tag"),
    16: .same(proto: "h5Tag"),
    17: .same(proto: "h6Tag"),
  ]

  fileprivate class _StorageClass {
    var _body: Color? = nil
    var _h1: Color? = nil
    var _h2: Color? = nil
    var _h3: Color? = nil
    var _h4: Color? = nil
    var _h5: Color? = nil
    var _h6: Color? = nil
    var _code: Color? = nil
    var _hr: Color? = nil
    var _blockquote: Color? = nil
    var _p: Color? = nil
    var _h1Tag: Color? = nil
    var _h2Tag: Color? = nil
    var _h3Tag: Color? = nil
    var _h4Tag: Color? = nil
    var _h5Tag: Color? = nil
    var _h6Tag: Color? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _body = source._body
      _h1 = source._h1
      _h2 = source._h2
      _h3 = source._h3
      _h4 = source._h4
      _h5 = source._h5
      _h6 = source._h6
      _code = source._code
      _hr = source._hr
      _blockquote = source._blockquote
      _p = source._p
      _h1Tag = source._h1Tag
      _h2Tag = source._h2Tag
      _h3Tag = source._h3Tag
      _h4Tag = source._h4Tag
      _h5Tag = source._h5Tag
      _h6Tag = source._h6Tag
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._body)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._h1)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._h2)
        case 4: try decoder.decodeSingularMessageField(value: &_storage._h3)
        case 5: try decoder.decodeSingularMessageField(value: &_storage._h4)
        case 6: try decoder.decodeSingularMessageField(value: &_storage._h5)
        case 7: try decoder.decodeSingularMessageField(value: &_storage._h6)
        case 8: try decoder.decodeSingularMessageField(value: &_storage._code)
        case 9: try decoder.decodeSingularMessageField(value: &_storage._hr)
        case 10: try decoder.decodeSingularMessageField(value: &_storage._blockquote)
        case 11: try decoder.decodeSingularMessageField(value: &_storage._p)
        case 12: try decoder.decodeSingularMessageField(value: &_storage._h1Tag)
        case 13: try decoder.decodeSingularMessageField(value: &_storage._h2Tag)
        case 14: try decoder.decodeSingularMessageField(value: &_storage._h3Tag)
        case 15: try decoder.decodeSingularMessageField(value: &_storage._h4Tag)
        case 16: try decoder.decodeSingularMessageField(value: &_storage._h5Tag)
        case 17: try decoder.decodeSingularMessageField(value: &_storage._h6Tag)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._body {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if let v = _storage._h1 {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
      if let v = _storage._h2 {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if let v = _storage._h3 {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
      if let v = _storage._h4 {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }
      if let v = _storage._h5 {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }
      if let v = _storage._h6 {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      }
      if let v = _storage._code {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      }
      if let v = _storage._hr {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      }
      if let v = _storage._blockquote {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      }
      if let v = _storage._p {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      }
      if let v = _storage._h1Tag {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      }
      if let v = _storage._h2Tag {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
      }
      if let v = _storage._h3Tag {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
      }
      if let v = _storage._h4Tag {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
      }
      if let v = _storage._h5Tag {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 16)
      }
      if let v = _storage._h6Tag {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 17)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: TextStylePreviewMetadata, rhs: TextStylePreviewMetadata) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._body != rhs_storage._body {return false}
        if _storage._h1 != rhs_storage._h1 {return false}
        if _storage._h2 != rhs_storage._h2 {return false}
        if _storage._h3 != rhs_storage._h3 {return false}
        if _storage._h4 != rhs_storage._h4 {return false}
        if _storage._h5 != rhs_storage._h5 {return false}
        if _storage._h6 != rhs_storage._h6 {return false}
        if _storage._code != rhs_storage._code {return false}
        if _storage._hr != rhs_storage._hr {return false}
        if _storage._blockquote != rhs_storage._blockquote {return false}
        if _storage._p != rhs_storage._p {return false}
        if _storage._h1Tag != rhs_storage._h1Tag {return false}
        if _storage._h2Tag != rhs_storage._h2Tag {return false}
        if _storage._h3Tag != rhs_storage._h3Tag {return false}
        if _storage._h4Tag != rhs_storage._h4Tag {return false}
        if _storage._h5Tag != rhs_storage._h5Tag {return false}
        if _storage._h6Tag != rhs_storage._h6Tag {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Color: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "Color"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "red"),
    2: .same(proto: "green"),
    3: .same(proto: "blue"),
    4: .same(proto: "alpha"),
  ]

  fileprivate class _StorageClass {
    var _red: Float = 0
    var _green: Float = 0
    var _blue: Float = 0
    var _alpha: SwiftProtobuf.Google_Protobuf_FloatValue? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _red = source._red
      _green = source._green
      _blue = source._blue
      _alpha = source._alpha
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularFloatField(value: &_storage._red)
        case 2: try decoder.decodeSingularFloatField(value: &_storage._green)
        case 3: try decoder.decodeSingularFloatField(value: &_storage._blue)
        case 4: try decoder.decodeSingularMessageField(value: &_storage._alpha)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._red != 0 {
        try visitor.visitSingularFloatField(value: _storage._red, fieldNumber: 1)
      }
      if _storage._green != 0 {
        try visitor.visitSingularFloatField(value: _storage._green, fieldNumber: 2)
      }
      if _storage._blue != 0 {
        try visitor.visitSingularFloatField(value: _storage._blue, fieldNumber: 3)
      }
      if let v = _storage._alpha {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Color, rhs: Color) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._red != rhs_storage._red {return false}
        if _storage._green != rhs_storage._green {return false}
        if _storage._blue != rhs_storage._blue {return false}
        if _storage._alpha != rhs_storage._alpha {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
