// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: stylo_1.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct SemanticVersion {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var major: UInt32 = 0

  public var minor: UInt32 = 0

  public var patch: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct StylesheetMetadata_1 {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// unique id of the stylesheet which correspond to the file name
  public var id: String = String()

  /// cannot assign a name to a stylesheet yet...
  /// but we define it ot minimize changes in the future
  public var title: String = String()

  public var order: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct StyleMetadata_1 {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// unique id of the style which correspond to the directory name
  public var id: String = String()

  public var title: String = String()

  public var stylesheets: Dictionary<String,StylesheetMetadata_1> = [:]

  public var order: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct StyleSetMetadata_1 {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var styles: Dictionary<String,StyleMetadata_1> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct WritingSessionMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var startDate: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._startDate ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._startDate = newValue}
  }
  /// Returns true if `startDate` has been explicitly set.
  public var hasStartDate: Bool {return _storage._startDate != nil}
  /// Clears the value of `startDate`. Subsequent reads from it will return its default value.
  public mutating func clearStartDate() {_uniqueStorage()._startDate = nil}

  public var charactersCount: Int32 {
    get {return _storage._charactersCount}
    set {_uniqueStorage()._charactersCount = newValue}
  }

  public var wordsCount: Int32 {
    get {return _storage._wordsCount}
    set {_uniqueStorage()._wordsCount = newValue}
  }

  public var sentencesCount: Int32 {
    get {return _storage._sentencesCount}
    set {_uniqueStorage()._sentencesCount = newValue}
  }

  public var paragraphsCount: Int32 {
    get {return _storage._paragraphsCount}
    set {_uniqueStorage()._paragraphsCount = newValue}
  }

  public var pagesCount: Float {
    get {return _storage._pagesCount}
    set {_uniqueStorage()._pagesCount = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct WritingSessionsMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var isHidden: Bool = false

  public var sessions: [WritingSessionMetadata] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct SourceMetadata_1 {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// unique id of the source which correspond to the file name
  public var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var title: String {
    get {return _storage._title}
    set {_uniqueStorage()._title = newValue}
  }

  public var order: UInt32 {
    get {return _storage._order}
    set {_uniqueStorage()._order = newValue}
  }

  /// since each source can have it's own style, each source
  /// is responsible to know it's own style.
  public var styleID: String {
    get {return _storage._styleID}
    set {_uniqueStorage()._styleID = newValue}
  }

  public var writingSessions: WritingSessionsMetadata {
    get {return _storage._writingSessions ?? WritingSessionsMetadata()}
    set {_uniqueStorage()._writingSessions = newValue}
  }
  /// Returns true if `writingSessions` has been explicitly set.
  public var hasWritingSessions: Bool {return _storage._writingSessions != nil}
  /// Clears the value of `writingSessions`. Subsequent reads from it will return its default value.
  public mutating func clearWritingSessions() {_uniqueStorage()._writingSessions = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct SourceSetMetadata_1 {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sources: Dictionary<String,SourceMetadata_1> = [:]

  public var selectedSourceID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DocumentMetadata_1 {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  public var releaseVersion: SemanticVersion {
    get {return _storage._releaseVersion ?? SemanticVersion()}
    set {_uniqueStorage()._releaseVersion = newValue}
  }
  /// Returns true if `releaseVersion` has been explicitly set.
  public var hasReleaseVersion: Bool {return _storage._releaseVersion != nil}
  /// Clears the value of `releaseVersion`. Subsequent reads from it will return its default value.
  public mutating func clearReleaseVersion() {_uniqueStorage()._releaseVersion = nil}

  public var sourceSet: SourceSetMetadata_1 {
    get {return _storage._sourceSet ?? SourceSetMetadata_1()}
    set {_uniqueStorage()._sourceSet = newValue}
  }
  /// Returns true if `sourceSet` has been explicitly set.
  public var hasSourceSet: Bool {return _storage._sourceSet != nil}
  /// Clears the value of `sourceSet`. Subsequent reads from it will return its default value.
  public mutating func clearSourceSet() {_uniqueStorage()._sourceSet = nil}

  public var styleSet: StyleSetMetadata_1 {
    get {return _storage._styleSet ?? StyleSetMetadata_1()}
    set {_uniqueStorage()._styleSet = newValue}
  }
  /// Returns true if `styleSet` has been explicitly set.
  public var hasStyleSet: Bool {return _storage._styleSet != nil}
  /// Clears the value of `styleSet`. Subsequent reads from it will return its default value.
  public mutating func clearStyleSet() {_uniqueStorage()._styleSet = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension SemanticVersion: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "SemanticVersion"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "major"),
    2: .same(proto: "minor"),
    3: .same(proto: "patch"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularUInt32Field(value: &self.major)
      case 2: try decoder.decodeSingularUInt32Field(value: &self.minor)
      case 3: try decoder.decodeSingularUInt32Field(value: &self.patch)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.major != 0 {
      try visitor.visitSingularUInt32Field(value: self.major, fieldNumber: 1)
    }
    if self.minor != 0 {
      try visitor.visitSingularUInt32Field(value: self.minor, fieldNumber: 2)
    }
    if self.patch != 0 {
      try visitor.visitSingularUInt32Field(value: self.patch, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SemanticVersion, rhs: SemanticVersion) -> Bool {
    if lhs.major != rhs.major {return false}
    if lhs.minor != rhs.minor {return false}
    if lhs.patch != rhs.patch {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension StylesheetMetadata_1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "StylesheetMetadata_1"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "title"),
    3: .same(proto: "order"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.id)
      case 2: try decoder.decodeSingularStringField(value: &self.title)
      case 3: try decoder.decodeSingularUInt32Field(value: &self.order)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if self.order != 0 {
      try visitor.visitSingularUInt32Field(value: self.order, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: StylesheetMetadata_1, rhs: StylesheetMetadata_1) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.title != rhs.title {return false}
    if lhs.order != rhs.order {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension StyleMetadata_1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "StyleMetadata_1"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "title"),
    3: .same(proto: "stylesheets"),
    4: .same(proto: "order"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.id)
      case 2: try decoder.decodeSingularStringField(value: &self.title)
      case 3: try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,StylesheetMetadata_1>.self, value: &self.stylesheets)
      case 4: try decoder.decodeSingularUInt32Field(value: &self.order)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if !self.stylesheets.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,StylesheetMetadata_1>.self, value: self.stylesheets, fieldNumber: 3)
    }
    if self.order != 0 {
      try visitor.visitSingularUInt32Field(value: self.order, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: StyleMetadata_1, rhs: StyleMetadata_1) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.title != rhs.title {return false}
    if lhs.stylesheets != rhs.stylesheets {return false}
    if lhs.order != rhs.order {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension StyleSetMetadata_1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "StyleSetMetadata_1"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "styles"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,StyleMetadata_1>.self, value: &self.styles)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.styles.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,StyleMetadata_1>.self, value: self.styles, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: StyleSetMetadata_1, rhs: StyleSetMetadata_1) -> Bool {
    if lhs.styles != rhs.styles {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension WritingSessionMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "WritingSessionMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "startDate"),
    2: .same(proto: "charactersCount"),
    3: .same(proto: "wordsCount"),
    4: .same(proto: "sentencesCount"),
    5: .same(proto: "paragraphsCount"),
    6: .same(proto: "pagesCount"),
  ]

  fileprivate class _StorageClass {
    var _startDate: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _charactersCount: Int32 = 0
    var _wordsCount: Int32 = 0
    var _sentencesCount: Int32 = 0
    var _paragraphsCount: Int32 = 0
    var _pagesCount: Float = 0

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _startDate = source._startDate
      _charactersCount = source._charactersCount
      _wordsCount = source._wordsCount
      _sentencesCount = source._sentencesCount
      _paragraphsCount = source._paragraphsCount
      _pagesCount = source._pagesCount
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._startDate)
        case 2: try decoder.decodeSingularInt32Field(value: &_storage._charactersCount)
        case 3: try decoder.decodeSingularInt32Field(value: &_storage._wordsCount)
        case 4: try decoder.decodeSingularInt32Field(value: &_storage._sentencesCount)
        case 5: try decoder.decodeSingularInt32Field(value: &_storage._paragraphsCount)
        case 6: try decoder.decodeSingularFloatField(value: &_storage._pagesCount)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._startDate {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if _storage._charactersCount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._charactersCount, fieldNumber: 2)
      }
      if _storage._wordsCount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._wordsCount, fieldNumber: 3)
      }
      if _storage._sentencesCount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._sentencesCount, fieldNumber: 4)
      }
      if _storage._paragraphsCount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._paragraphsCount, fieldNumber: 5)
      }
      if _storage._pagesCount != 0 {
        try visitor.visitSingularFloatField(value: _storage._pagesCount, fieldNumber: 6)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: WritingSessionMetadata, rhs: WritingSessionMetadata) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._startDate != rhs_storage._startDate {return false}
        if _storage._charactersCount != rhs_storage._charactersCount {return false}
        if _storage._wordsCount != rhs_storage._wordsCount {return false}
        if _storage._sentencesCount != rhs_storage._sentencesCount {return false}
        if _storage._paragraphsCount != rhs_storage._paragraphsCount {return false}
        if _storage._pagesCount != rhs_storage._pagesCount {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension WritingSessionsMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "WritingSessionsMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "isHidden"),
    2: .same(proto: "sessions"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularBoolField(value: &self.isHidden)
      case 2: try decoder.decodeRepeatedMessageField(value: &self.sessions)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.isHidden != false {
      try visitor.visitSingularBoolField(value: self.isHidden, fieldNumber: 1)
    }
    if !self.sessions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.sessions, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: WritingSessionsMetadata, rhs: WritingSessionsMetadata) -> Bool {
    if lhs.isHidden != rhs.isHidden {return false}
    if lhs.sessions != rhs.sessions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SourceMetadata_1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "SourceMetadata_1"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "title"),
    3: .same(proto: "order"),
    4: .same(proto: "styleId"),
    5: .same(proto: "writingSessions"),
  ]

  fileprivate class _StorageClass {
    var _id: String = String()
    var _title: String = String()
    var _order: UInt32 = 0
    var _styleID: String = String()
    var _writingSessions: WritingSessionsMetadata? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _title = source._title
      _order = source._order
      _styleID = source._styleID
      _writingSessions = source._writingSessions
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &_storage._id)
        case 2: try decoder.decodeSingularStringField(value: &_storage._title)
        case 3: try decoder.decodeSingularUInt32Field(value: &_storage._order)
        case 4: try decoder.decodeSingularStringField(value: &_storage._styleID)
        case 5: try decoder.decodeSingularMessageField(value: &_storage._writingSessions)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._title.isEmpty {
        try visitor.visitSingularStringField(value: _storage._title, fieldNumber: 2)
      }
      if _storage._order != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._order, fieldNumber: 3)
      }
      if !_storage._styleID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._styleID, fieldNumber: 4)
      }
      if let v = _storage._writingSessions {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SourceMetadata_1, rhs: SourceMetadata_1) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._title != rhs_storage._title {return false}
        if _storage._order != rhs_storage._order {return false}
        if _storage._styleID != rhs_storage._styleID {return false}
        if _storage._writingSessions != rhs_storage._writingSessions {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SourceSetMetadata_1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "SourceSetMetadata_1"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "sources"),
    2: .same(proto: "selectedSourceId"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SourceMetadata_1>.self, value: &self.sources)
      case 2: try decoder.decodeSingularStringField(value: &self.selectedSourceID)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sources.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SourceMetadata_1>.self, value: self.sources, fieldNumber: 1)
    }
    if !self.selectedSourceID.isEmpty {
      try visitor.visitSingularStringField(value: self.selectedSourceID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SourceSetMetadata_1, rhs: SourceSetMetadata_1) -> Bool {
    if lhs.sources != rhs.sources {return false}
    if lhs.selectedSourceID != rhs.selectedSourceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DocumentMetadata_1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "DocumentMetadata_1"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .same(proto: "releaseVersion"),
    3: .same(proto: "sourceSet"),
    4: .same(proto: "styleSet"),
  ]

  fileprivate class _StorageClass {
    var _name: String = String()
    var _releaseVersion: SemanticVersion? = nil
    var _sourceSet: SourceSetMetadata_1? = nil
    var _styleSet: StyleSetMetadata_1? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _name = source._name
      _releaseVersion = source._releaseVersion
      _sourceSet = source._sourceSet
      _styleSet = source._styleSet
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &_storage._name)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._releaseVersion)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._sourceSet)
        case 4: try decoder.decodeSingularMessageField(value: &_storage._styleSet)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 1)
      }
      if let v = _storage._releaseVersion {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
      if let v = _storage._sourceSet {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if let v = _storage._styleSet {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DocumentMetadata_1, rhs: DocumentMetadata_1) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._name != rhs_storage._name {return false}
        if _storage._releaseVersion != rhs_storage._releaseVersion {return false}
        if _storage._sourceSet != rhs_storage._sourceSet {return false}
        if _storage._styleSet != rhs_storage._styleSet {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
