// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: stylo.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct FileMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  /// the path of this element relative to the document
  /// it includes the file name
  public var name: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DirectoryMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  /// the path of this element relative to the document
  /// it includes the file name
  public var name: String = String()

  public var items: [DirectoryItemMetadata] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DirectoryItemMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var item: OneOf_Item? {
    get {return _storage._item}
    set {_uniqueStorage()._item = newValue}
  }

  public var file: FileMetadata {
    get {
      if case .file(let v)? = _storage._item {return v}
      return FileMetadata()
    }
    set {_uniqueStorage()._item = .file(newValue)}
  }

  public var directory: DirectoryMetadata {
    get {
      if case .directory(let v)? = _storage._item {return v}
      return DirectoryMetadata()
    }
    set {_uniqueStorage()._item = .directory(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Item: Equatable {
    case file(FileMetadata)
    case directory(DirectoryMetadata)

  #if !swift(>=4.1)
    public static func ==(lhs: DirectoryItemMetadata.OneOf_Item, rhs: DirectoryItemMetadata.OneOf_Item) -> Bool {
      switch (lhs, rhs) {
      case (.file(let l), .file(let r)): return l == r
      case (.directory(let l), .directory(let r)): return l == r
      default: return false
      }
    }
  #endif
  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct ExternalFilesSetMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct SourceSetMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// external files, here because we need all files id
  /// to be defined in the source set manager
  /// repeated ExternalFilesGroup externalGroups = 3;
  public var items: [DirectoryItemMetadata] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct FilesOutlineMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var name: String = String()

  /// Array of all files outline user selected items.
  public var outlineUserSelectedItems: [String] = []

  /// Array of all files outline expanded items.
  public var outlineExpandedItems: [String] = []

  /// Array of all editors array collapsed items
  /// Note: this is not the outline.
  public var collapsedEditorItems: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct FilesOutlineSetMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var selectedFilesOutlineID: String = String()

  public var filesOutlines: [FilesOutlineMetadata] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DocumentMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  public var releaseVersion: SemanticVersion {
    get {return _storage._releaseVersion ?? SemanticVersion()}
    set {_uniqueStorage()._releaseVersion = newValue}
  }
  /// Returns true if `releaseVersion` has been explicitly set.
  public var hasReleaseVersion: Bool {return _storage._releaseVersion != nil}
  /// Clears the value of `releaseVersion`. Subsequent reads from it will return its default value.
  public mutating func clearReleaseVersion() {_uniqueStorage()._releaseVersion = nil}

  public var sourceSet: SourceSetMetadata {
    get {return _storage._sourceSet ?? SourceSetMetadata()}
    set {_uniqueStorage()._sourceSet = newValue}
  }
  /// Returns true if `sourceSet` has been explicitly set.
  public var hasSourceSet: Bool {return _storage._sourceSet != nil}
  /// Clears the value of `sourceSet`. Subsequent reads from it will return its default value.
  public mutating func clearSourceSet() {_uniqueStorage()._sourceSet = nil}

  public var filesOutlineSet: FilesOutlineSetMetadata {
    get {return _storage._filesOutlineSet ?? FilesOutlineSetMetadata()}
    set {_uniqueStorage()._filesOutlineSet = newValue}
  }
  /// Returns true if `filesOutlineSet` has been explicitly set.
  public var hasFilesOutlineSet: Bool {return _storage._filesOutlineSet != nil}
  /// Clears the value of `filesOutlineSet`. Subsequent reads from it will return its default value.
  public mutating func clearFilesOutlineSet() {_uniqueStorage()._filesOutlineSet = nil}

  public var formatVersion: SemanticVersion {
    get {return _storage._formatVersion ?? SemanticVersion()}
    set {_uniqueStorage()._formatVersion = newValue}
  }
  /// Returns true if `formatVersion` has been explicitly set.
  public var hasFormatVersion: Bool {return _storage._formatVersion != nil}
  /// Clears the value of `formatVersion`. Subsequent reads from it will return its default value.
  public mutating func clearFormatVersion() {_uniqueStorage()._formatVersion = nil}

  public var globalStyleID: String {
    get {return _storage._globalStyleID}
    set {_uniqueStorage()._globalStyleID = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension FileMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "FileMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.id)
      case 2: try decoder.decodeSingularStringField(value: &self.name)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: FileMetadata, rhs: FileMetadata) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DirectoryMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "DirectoryMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
    3: .same(proto: "items"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.id)
      case 2: try decoder.decodeSingularStringField(value: &self.name)
      case 3: try decoder.decodeRepeatedMessageField(value: &self.items)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.items.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.items, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DirectoryMetadata, rhs: DirectoryMetadata) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.items != rhs.items {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DirectoryItemMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "DirectoryItemMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "file"),
    2: .same(proto: "directory"),
  ]

  fileprivate class _StorageClass {
    var _item: DirectoryItemMetadata.OneOf_Item?

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _item = source._item
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1:
          var v: FileMetadata?
          if let current = _storage._item {
            try decoder.handleConflictingOneOf()
            if case .file(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._item = .file(v)}
        case 2:
          var v: DirectoryMetadata?
          if let current = _storage._item {
            try decoder.handleConflictingOneOf()
            if case .directory(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {_storage._item = .directory(v)}
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      switch _storage._item {
      case .file(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      case .directory(let v)?:
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      case nil: break
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DirectoryItemMetadata, rhs: DirectoryItemMetadata) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._item != rhs_storage._item {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ExternalFilesSetMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "ExternalFilesSetMetadata"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ExternalFilesSetMetadata, rhs: ExternalFilesSetMetadata) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SourceSetMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "SourceSetMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "items"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.items)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.items.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.items, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SourceSetMetadata, rhs: SourceSetMetadata) -> Bool {
    if lhs.items != rhs.items {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FilesOutlineMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "FilesOutlineMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
    3: .same(proto: "outlineUserSelectedItems"),
    4: .same(proto: "outlineExpandedItems"),
    5: .same(proto: "collapsedEditorItems"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.id)
      case 2: try decoder.decodeSingularStringField(value: &self.name)
      case 3: try decoder.decodeRepeatedStringField(value: &self.outlineUserSelectedItems)
      case 4: try decoder.decodeRepeatedStringField(value: &self.outlineExpandedItems)
      case 5: try decoder.decodeRepeatedStringField(value: &self.collapsedEditorItems)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.outlineUserSelectedItems.isEmpty {
      try visitor.visitRepeatedStringField(value: self.outlineUserSelectedItems, fieldNumber: 3)
    }
    if !self.outlineExpandedItems.isEmpty {
      try visitor.visitRepeatedStringField(value: self.outlineExpandedItems, fieldNumber: 4)
    }
    if !self.collapsedEditorItems.isEmpty {
      try visitor.visitRepeatedStringField(value: self.collapsedEditorItems, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: FilesOutlineMetadata, rhs: FilesOutlineMetadata) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.outlineUserSelectedItems != rhs.outlineUserSelectedItems {return false}
    if lhs.outlineExpandedItems != rhs.outlineExpandedItems {return false}
    if lhs.collapsedEditorItems != rhs.collapsedEditorItems {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FilesOutlineSetMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "FilesOutlineSetMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "selectedFilesOutlineId"),
    3: .same(proto: "filesOutlines"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.id)
      case 2: try decoder.decodeSingularStringField(value: &self.selectedFilesOutlineID)
      case 3: try decoder.decodeRepeatedMessageField(value: &self.filesOutlines)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.selectedFilesOutlineID.isEmpty {
      try visitor.visitSingularStringField(value: self.selectedFilesOutlineID, fieldNumber: 2)
    }
    if !self.filesOutlines.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.filesOutlines, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: FilesOutlineSetMetadata, rhs: FilesOutlineSetMetadata) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.selectedFilesOutlineID != rhs.selectedFilesOutlineID {return false}
    if lhs.filesOutlines != rhs.filesOutlines {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DocumentMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "DocumentMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
    3: .same(proto: "releaseVersion"),
    4: .same(proto: "sourceSet"),
    5: .same(proto: "filesOutlineSet"),
    6: .same(proto: "formatVersion"),
    7: .same(proto: "globalStyleId"),
  ]

  fileprivate class _StorageClass {
    var _id: String = String()
    var _name: String = String()
    var _releaseVersion: SemanticVersion? = nil
    var _sourceSet: SourceSetMetadata? = nil
    var _filesOutlineSet: FilesOutlineSetMetadata? = nil
    var _formatVersion: SemanticVersion? = nil
    var _globalStyleID: String = String()

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _name = source._name
      _releaseVersion = source._releaseVersion
      _sourceSet = source._sourceSet
      _filesOutlineSet = source._filesOutlineSet
      _formatVersion = source._formatVersion
      _globalStyleID = source._globalStyleID
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &_storage._id)
        case 2: try decoder.decodeSingularStringField(value: &_storage._name)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._releaseVersion)
        case 4: try decoder.decodeSingularMessageField(value: &_storage._sourceSet)
        case 5: try decoder.decodeSingularMessageField(value: &_storage._filesOutlineSet)
        case 6: try decoder.decodeSingularMessageField(value: &_storage._formatVersion)
        case 7: try decoder.decodeSingularStringField(value: &_storage._globalStyleID)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 2)
      }
      if let v = _storage._releaseVersion {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if let v = _storage._sourceSet {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
      if let v = _storage._filesOutlineSet {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }
      if let v = _storage._formatVersion {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }
      if !_storage._globalStyleID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._globalStyleID, fieldNumber: 7)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DocumentMetadata, rhs: DocumentMetadata) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._releaseVersion != rhs_storage._releaseVersion {return false}
        if _storage._sourceSet != rhs_storage._sourceSet {return false}
        if _storage._filesOutlineSet != rhs_storage._filesOutlineSet {return false}
        if _storage._formatVersion != rhs_storage._formatVersion {return false}
        if _storage._globalStyleID != rhs_storage._globalStyleID {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
