// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: stylo_audio_plugin.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum AudioFormat: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case unknownAudioFormat // = 0
  case pcm // = 1
  case applelosseless // = 2
  case flac // = 3
  case mpeg4Aac // = 4
  case amr // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknownAudioFormat
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknownAudioFormat
    case 1: self = .pcm
    case 2: self = .applelosseless
    case 3: self = .flac
    case 4: self = .mpeg4Aac
    case 5: self = .amr
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknownAudioFormat: return 0
    case .pcm: return 1
    case .applelosseless: return 2
    case .flac: return 3
    case .mpeg4Aac: return 4
    case .amr: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension AudioFormat: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [AudioFormat] = [
    .unknownAudioFormat,
    .pcm,
    .applelosseless,
    .flac,
    .mpeg4Aac,
    .amr,
  ]
}

#endif  // swift(>=4.2)

public enum AudioQuality: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case unknownAudioQuality // = 0
  case min // = 1
  case low // = 2
  case medium // = 3
  case high // = 4
  case max // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknownAudioQuality
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknownAudioQuality
    case 1: self = .min
    case 2: self = .low
    case 3: self = .medium
    case 4: self = .high
    case 5: self = .max
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknownAudioQuality: return 0
    case .min: return 1
    case .low: return 2
    case .medium: return 3
    case .high: return 4
    case .max: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension AudioQuality: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [AudioQuality] = [
    .unknownAudioQuality,
    .min,
    .low,
    .medium,
    .high,
    .max,
  ]
}

#endif  // swift(>=4.2)

public enum ChannelsMode: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case unknownChannelsMode // = 0
  case mono // = 1
  case stereo // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknownChannelsMode
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknownChannelsMode
    case 1: self = .mono
    case 2: self = .stereo
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknownChannelsMode: return 0
    case .mono: return 1
    case .stereo: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension ChannelsMode: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [ChannelsMode] = [
    .unknownChannelsMode,
    .mono,
    .stereo,
  ]
}

#endif  // swift(>=4.2)

public enum AudioPlayerState: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case unknownAudioPlayerState // = 0
  case player // = 1
  case recorder // = 2
  case notShow // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknownAudioPlayerState
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknownAudioPlayerState
    case 1: self = .player
    case 2: self = .recorder
    case 3: self = .notShow
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknownAudioPlayerState: return 0
    case .player: return 1
    case .recorder: return 2
    case .notShow: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension AudioPlayerState: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [AudioPlayerState] = [
    .unknownAudioPlayerState,
    .player,
    .recorder,
    .notShow,
  ]
}

#endif  // swift(>=4.2)

public struct AudioFileMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  public var recordedDate: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._recordedDate ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._recordedDate = newValue}
  }
  /// Returns true if `recordedDate` has been explicitly set.
  public var hasRecordedDate: Bool {return _storage._recordedDate != nil}
  /// Clears the value of `recordedDate`. Subsequent reads from it will return its default value.
  public mutating func clearRecordedDate() {_uniqueStorage()._recordedDate = nil}

  public var audioFormat: AudioFormat {
    get {return _storage._audioFormat}
    set {_uniqueStorage()._audioFormat = newValue}
  }

  public var sampleRate: UInt32 {
    get {return _storage._sampleRate}
    set {_uniqueStorage()._sampleRate = newValue}
  }

  public var mode: ChannelsMode {
    get {return _storage._mode}
    set {_uniqueStorage()._mode = newValue}
  }

  public var audioQuality: AudioQuality {
    get {return _storage._audioQuality}
    set {_uniqueStorage()._audioQuality = newValue}
  }

  public var audioPlayerState: AudioPlayerState {
    get {return _storage._audioPlayerState}
    set {_uniqueStorage()._audioPlayerState = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct DocumentAudioFilesMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var associatedDocumentID: String = String()

  public var audioFiles: [AudioFileMetadata] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct AudioFilesOutlineMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var name: String = String()

  /// contains the ids of the elements
  public var expandedItems: [String] = []

  /// contains the id of the selected element
  /// it can either be: Document or Audio.
  public var selectedItem: String = String()

  public var selectedFilesFilterActive: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct AudioFilesMetadata {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var documentAudioFiles: [DocumentAudioFilesMetadata] {
    get {return _storage._documentAudioFiles}
    set {_uniqueStorage()._documentAudioFiles = newValue}
  }

  public var audioFilesOutline: AudioFilesOutlineMetadata {
    get {return _storage._audioFilesOutline ?? AudioFilesOutlineMetadata()}
    set {_uniqueStorage()._audioFilesOutline = newValue}
  }
  /// Returns true if `audioFilesOutline` has been explicitly set.
  public var hasAudioFilesOutline: Bool {return _storage._audioFilesOutline != nil}
  /// Clears the value of `audioFilesOutline`. Subsequent reads from it will return its default value.
  public mutating func clearAudioFilesOutline() {_uniqueStorage()._audioFilesOutline = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension AudioFormat: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNKNOWN_AUDIO_FORMAT"),
    1: .same(proto: "PCM"),
    2: .same(proto: "APPLELOSSELESS"),
    3: .same(proto: "FLAC"),
    4: .same(proto: "MPEG4AAC"),
    5: .same(proto: "AMR"),
  ]
}

extension AudioQuality: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNKNOWN_AUDIO_QUALITY"),
    1: .same(proto: "MIN"),
    2: .same(proto: "LOW"),
    3: .same(proto: "MEDIUM"),
    4: .same(proto: "HIGH"),
    5: .same(proto: "MAX"),
  ]
}

extension ChannelsMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNKNOWN_CHANNELS_MODE"),
    1: .same(proto: "MONO"),
    2: .same(proto: "STEREO"),
  ]
}

extension AudioPlayerState: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNKNOWN_AUDIO_PLAYER_STATE"),
    1: .same(proto: "PLAYER"),
    2: .same(proto: "RECORDER"),
    3: .same(proto: "NOT_SHOW"),
  ]
}

extension AudioFileMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "AudioFileMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
    3: .same(proto: "recordedDate"),
    4: .same(proto: "audioFormat"),
    5: .same(proto: "sampleRate"),
    6: .same(proto: "mode"),
    7: .same(proto: "audioQuality"),
    8: .same(proto: "audioPlayerState"),
  ]

  fileprivate class _StorageClass {
    var _id: String = String()
    var _name: String = String()
    var _recordedDate: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _audioFormat: AudioFormat = .unknownAudioFormat
    var _sampleRate: UInt32 = 0
    var _mode: ChannelsMode = .unknownChannelsMode
    var _audioQuality: AudioQuality = .unknownAudioQuality
    var _audioPlayerState: AudioPlayerState = .unknownAudioPlayerState

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _name = source._name
      _recordedDate = source._recordedDate
      _audioFormat = source._audioFormat
      _sampleRate = source._sampleRate
      _mode = source._mode
      _audioQuality = source._audioQuality
      _audioPlayerState = source._audioPlayerState
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &_storage._id)
        case 2: try decoder.decodeSingularStringField(value: &_storage._name)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._recordedDate)
        case 4: try decoder.decodeSingularEnumField(value: &_storage._audioFormat)
        case 5: try decoder.decodeSingularUInt32Field(value: &_storage._sampleRate)
        case 6: try decoder.decodeSingularEnumField(value: &_storage._mode)
        case 7: try decoder.decodeSingularEnumField(value: &_storage._audioQuality)
        case 8: try decoder.decodeSingularEnumField(value: &_storage._audioPlayerState)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 2)
      }
      if let v = _storage._recordedDate {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if _storage._audioFormat != .unknownAudioFormat {
        try visitor.visitSingularEnumField(value: _storage._audioFormat, fieldNumber: 4)
      }
      if _storage._sampleRate != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._sampleRate, fieldNumber: 5)
      }
      if _storage._mode != .unknownChannelsMode {
        try visitor.visitSingularEnumField(value: _storage._mode, fieldNumber: 6)
      }
      if _storage._audioQuality != .unknownAudioQuality {
        try visitor.visitSingularEnumField(value: _storage._audioQuality, fieldNumber: 7)
      }
      if _storage._audioPlayerState != .unknownAudioPlayerState {
        try visitor.visitSingularEnumField(value: _storage._audioPlayerState, fieldNumber: 8)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AudioFileMetadata, rhs: AudioFileMetadata) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._recordedDate != rhs_storage._recordedDate {return false}
        if _storage._audioFormat != rhs_storage._audioFormat {return false}
        if _storage._sampleRate != rhs_storage._sampleRate {return false}
        if _storage._mode != rhs_storage._mode {return false}
        if _storage._audioQuality != rhs_storage._audioQuality {return false}
        if _storage._audioPlayerState != rhs_storage._audioPlayerState {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DocumentAudioFilesMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "DocumentAudioFilesMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "associatedDocumentId"),
    3: .same(proto: "audioFiles"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.id)
      case 2: try decoder.decodeSingularStringField(value: &self.associatedDocumentID)
      case 3: try decoder.decodeRepeatedMessageField(value: &self.audioFiles)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.associatedDocumentID.isEmpty {
      try visitor.visitSingularStringField(value: self.associatedDocumentID, fieldNumber: 2)
    }
    if !self.audioFiles.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.audioFiles, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DocumentAudioFilesMetadata, rhs: DocumentAudioFilesMetadata) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.associatedDocumentID != rhs.associatedDocumentID {return false}
    if lhs.audioFiles != rhs.audioFiles {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AudioFilesOutlineMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "AudioFilesOutlineMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
    3: .same(proto: "expandedItems"),
    4: .same(proto: "selectedItem"),
    5: .same(proto: "selectedFilesFilterActive"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.id)
      case 2: try decoder.decodeSingularStringField(value: &self.name)
      case 3: try decoder.decodeRepeatedStringField(value: &self.expandedItems)
      case 4: try decoder.decodeSingularStringField(value: &self.selectedItem)
      case 5: try decoder.decodeSingularBoolField(value: &self.selectedFilesFilterActive)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.expandedItems.isEmpty {
      try visitor.visitRepeatedStringField(value: self.expandedItems, fieldNumber: 3)
    }
    if !self.selectedItem.isEmpty {
      try visitor.visitSingularStringField(value: self.selectedItem, fieldNumber: 4)
    }
    if self.selectedFilesFilterActive != false {
      try visitor.visitSingularBoolField(value: self.selectedFilesFilterActive, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AudioFilesOutlineMetadata, rhs: AudioFilesOutlineMetadata) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.expandedItems != rhs.expandedItems {return false}
    if lhs.selectedItem != rhs.selectedItem {return false}
    if lhs.selectedFilesFilterActive != rhs.selectedFilesFilterActive {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AudioFilesMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "AudioFilesMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "documentAudioFiles"),
    3: .same(proto: "audioFilesOutline"),
  ]

  fileprivate class _StorageClass {
    var _id: String = String()
    var _documentAudioFiles: [DocumentAudioFilesMetadata] = []
    var _audioFilesOutline: AudioFilesOutlineMetadata? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _documentAudioFiles = source._documentAudioFiles
      _audioFilesOutline = source._audioFilesOutline
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &_storage._id)
        case 2: try decoder.decodeRepeatedMessageField(value: &_storage._documentAudioFiles)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._audioFilesOutline)
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._documentAudioFiles.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._documentAudioFiles, fieldNumber: 2)
      }
      if let v = _storage._audioFilesOutline {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AudioFilesMetadata, rhs: AudioFilesMetadata) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._documentAudioFiles != rhs_storage._documentAudioFiles {return false}
        if _storage._audioFilesOutline != rhs_storage._audioFilesOutline {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
